export enum UserPermission {
  APPROVE_VACATIONS = 'APPROVE_VACATIONS',
  APPROVE_REQUESTS = 'APPROVE_REQUESTS',
  VIEW_ALL_EMPLOYEES = 'VIEW_ALL_EMPLOYEES',
  MANAGE_PAYROLL = 'MANAGE_PAYROLL',
  MANAGE_EMPLOYEES = 'MANAGE_EMPLOYEES',
  MANAGE_DEPARTMENTS = 'MANAGE_DEPARTMENTS',
  MANAGE_BENEFITS = 'MANAGE_BENEFITS',
  VIEW_REPORTS = 'VIEW_REPORTS',
}
